config/routes.rb
Rails.application.routes.draw do

  
#Customer
  root to: 'pages#index'
  get 'about', to: 'pages#about'
  get 'coupons/checking/:code', action: :checking, controller: 'coupons'
  post 'cekstatus', to: 'cart_products#check'

  resource :comments
  # resources :users, only: [:edit, :update]
  resources :users, only: :index do
    collection do
      get 'profile'
      put 'update'
    end
  end

  resources :wallet_statuses
  resources :carts do
    member do
      post 'create_transaction'
      post 'change_quantity'
    end
  end 
  
  resources :orders do
    member do
      patch 'cancel'
      patch "transition"
    end
  end

  resources :cart_products do
    member do
      post :change_quantity
    end
  end
  
  resources :notifications, only: [:index]

  devise_for :users
  resources :products do
    member do
        post 'add_cart_product'
        post 'create_comment'
      end
    end
  
  


	#ADMIN
	namespace :admins do
		get 'pages/index' => 'pages#index'
		resources :products do
      member do
        post "create_comment"
        patch 'set_active'
        patch 'set_deactive'
      end
    end

    resources :orders, except: [:new, :destroy] do
       member do
        get "input_receiver"
        get "input_receipt" 
        patch "transition"
      end
    end
    resources :notifications, only: [:index, :show]
    resources :extra_charges, only: [:edit, :update]

		resources :coupons
    resources :service_charges 
    resources :wallet_statuses, only: [:index, :edit, :update] do
      member do 
        patch 'success'
        patch 'failed'
      end
    end
	end
  end

app/models/cart_product.rb
# == Schema Information
#
# Table name: cart_products
#
#  id         :bigint           not null, primary key
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cart_id    :bigint           not null
#  product_id :bigint           not null
#
# Indexes
#
#  index_cart_products_on_cart_id     (cart_id)
#  index_cart_products_on_product_id  (product_id)
#
# Foreign Keys
#
#  fk_rails_...  (cart_id => carts.id)
#  fk_rails_...  (product_id => products.id)
#
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  after_create  :update_price
  after_update :update_price
  after_destroy :update_price

  def update_price
    cart.sum
  end
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :set_cart_products
  before_action :set_coupon, only: [:index]
  before_action :set_cart_product, only: [:destroy, :edit, :update, :change_quantity]
  def index
  
  end

  def new
    @cart_product = CartProduct.new
  end

  def check
    	@code = Coupon.find_by("qty > ? and disable = ? and name = ?", 0, false, params[:code])
    	if @code.present?
    		flash[:notice] = "Code Has Been Submitted"
    	else
    		flash[:notice] = "Code not Valid"
    	end
      redirect_to cart_products_path(coupon: @code.id)
    end
 
    def destroy
    @cart_product.destroy
    respond_to do |format|
      format.html { redirect_to cart_products_path, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def change_quantity
    qty = params[:qty]
    @cart_product.update(quantity: qty)
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Only allow a list of trusted parameters through.
   
    def set_coupon
      if params["coupon"].present?
        @coupon = params["coupon"]
      end
    end
  
    def set_cart_product
      @cart_product = CartProduct.find(params[:id])
    end

    def cart_product_params
      params.require(:cart_product).permit(:cart_id, :product_id, :quantity)
    end

    def set_cart_products
      if current_user.carts.where(active:true).last.present?
        @cart_products = current_user.carts.where(active:true).last.cart_products
      else
        @cart_products = []
      end
    end
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/change_quantity.js.erb
$('#product_total_<%= @cart_product.id %>').html("<%= number_to_currency(@cart_product.quantity * @cart_product.product.price , :locale => :id) %>");
$('#cart-subtotal').text("<%=number_to_currency(@cart_product.cart.price, :locale => :id) %>");
$('#cart-total').text("<%=number_to_currency(@cart_product.cart.price, :locale => :id) %>");

app/views/cart_products/index.html.erb
  <!-- Breadcrumb Section Begin -->
<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <div class="breadcrumb__text">
          <h2>Shopping Cart</h2>
          <div class="breadcrumb__option">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Shoping Cart Section Begin -->
<section class="shoping-cart spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="shoping__cart__table">
          <table>
            <%if @cart_products.empty?%>
              <h5>Carts Empty</h5>
            <%else%>
              <thead>
                <tr>
                  <th class="shoping__product">Products</th>
                  <th>Price</th>
                  <th>Quantity</th>
                  <th>Total</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <%@cart_products.each do |product|%>
                  <tr id="<%= product.id %>" data-price="<%= product.product.price %>" class=".product">
                    <td class="shoping__cart__item">
                      <%if product.product.image.present?%>
                        <img src=<%= product.product.image.thumb %> alt="">
                      <%else%>
                        <img src=<%= asset_url('no_image.jpeg') %> alt="">
                      <%end%>
                      <h5><%=product.product.name.capitalize%></h5>
                    </td>
                    <td class="shoping__cart__price">
                      <%=number_to_currency(product.product.price, :locale => :id)%>
                    </td>
                    <td class="shoping__cart__quantity">
                      <div class="quantity">
                        <div class="pro-qty">
                          <input type="text" class="product-qty" value="<%=product.quantity%>">
                        </div>
                      </div>
                    </td>
                    <td class="shoping__cart__total" id="product_total_<%= product.id %>">
                      <%=number_to_currency(product.quantity * product.product.price , :locale => :id)%>
                    </td>
                    <td class="shoping__cart__item__close">
                      <%= link_to cart_product_path(product), method: :delete, data: {confirm: "Are you sure?"} do%>
                        <i class="fa fa-times"></i>
                      <%end%>
                    </td>
                  </tr>
                <%end%>
              </tbody>
            <%end%>
          </table>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="shoping__cart__btns">
          <a href="/" class="primary-btn cart-btn cart-btn-right">CONTINUE SHOPPING</a>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="shoping__continue">
          <div class="shoping__discount">
            <h5>Discount Codes</h5>
            <%= form_tag cekstatus_path, method: :post, remote: true do %>
              <div class="form-group">
                <%= text_field_tag :code, "", class: 'form-control'%>
                <button type="submit" class="site-btn" id="submit-voucher">APPLY COUPON</button>
              </div>
            <%end%>
            <button class="site-btn" id="checking-voucher">CHECK VOUCHER</button>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="shoping__checkout">
          <h5>Cart Total</h5>
          <%if @cart_products.present?%>
            <ul>
              <li>Subtotal <span id="cart-subtotal"><%=number_to_currency(@cart_products.first.cart.price, :locale => :id)%></span></li>
              <li>Total <span id="cart-total"><%=number_to_currency(@cart_products.first.cart.price, :locale => :id)%></span></li>
            </ul>
            <%= form_tag create_transaction_cart_path(@cart_products.first.cart, :coupon => @coupon), remote: true do %>
              <button class="primary-btn">PROCEED TO CHECKOUT</button>
            <%end%>
          <%else%>
            <ul>
              <li>Subtotal <span><%=number_to_currency(0, :locale => :id)%></span></li>
              <li>Total <span><%=number_to_currency(0, :locale => :id)%></span></li>
            </ul>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</section>
<%= content_for :script do %>
  <script>
    $( document ).ready(function() {
    $('#submit-voucher').hide();
    
    $('#checking-voucher').on('click', function(){
      $.ajax({
        url: "/coupons/checking/"+$('#code').val(),
        type: "GET",
        success: function(data){
           alert("Code Verified");
          $('#submit-voucher').show();
          $('#checking-voucher').hide();
        },
        error: function(err){
          alert("Code not found");
        }
      });
    });
      });
    
      $(document).on('turbolinks:load', function(){
          $('.qtybtn').on('click', function(){
              var parent = $(this).parentsUntil(".product")[3];
              var $button = $(this);
              var id = parent.id;
              var oldValue = $button.parent().find('input').val();
              if ($button.hasClass('inc')) {
                  var newVal = parseFloat(oldValue) + 1;
              } else {
                  // Don't allow decrementing below one
                  if (oldValue > 1) {
                      var newVal = parseFloat(oldValue) - 1;
                  } else {
                      newVal = 1;
                  }
              }
              updateQuantity(id, newVal);
          });
    
          $('.product-qty').on('change', function(){
              var parent = $(this).parentsUntil(".product")[3];
              var id = parent.id;
              var qty = $(this).val();
              updateQuantity(id, qty);
          });
    
          function updateQuantity(id, qty){
              var path = "<%= change_quantity_cart_product_path(":id") %>";
              var token = $( 'meta[name="csrf-token"]' ).attr( 'content' );
              $.ajax({
                  method: "POST",
                  url: path.replace(":id", id),
                  data: {qty: qty},
                  beforeSend: function ( xhr ) {
                      xhr.setRequestHeader( 'X-CSRF-Token', token );
                  }
              });
          }
      });
  </script>
<% end %>