config/routes.rb
Rails.application.routes.draw do

  
#Customer
  root to: 'pages#index'
  get 'about', to: 'pages#about'
  get 'coupons/checking/:code', action: :checking, controller: 'coupons'
  post 'cekstatus', to: 'cart_products#check'

  resource :comments
  # resources :users, only: [:edit, :update]
  resources :users, only: :index do
    collection do
      get 'profile'
      put 'update'
    end
  end

  resources :wallet_statuses
  resources :carts do
    member do
      post 'create_transaction'
      post 'change_quantity'
    end
  end 
  
  resources :orders do
    member do
      patch 'cancel'
      patch "transition"
    end
  end

  resources :cart_products do
    member do
      post :change_quantity
    end
  end
  
  resources :notifications, only: [:index]

  devise_for :users
  resources :products do
    member do
        post 'add_cart_product'
        post 'create_comment'
      end
    end
  
  


	#ADMIN
	namespace :admins do
		get 'pages/index' => 'pages#index'
		resources :products do
      member do
        post "create_comment"
        patch 'set_active'
        patch 'set_deactive'
      end
    end

    resources :orders, except: [:new, :destroy] do
       member do
        get "input_receiver"
        get "input_receipt" 
        patch "transition"
      end
    end
    resources :notifications, only: [:index, :show]
    resources :extra_charges, only: [:edit, :update]

		resources :coupons
    resources :service_charges 
    resources :wallet_statuses, only: [:index, :edit, :update] do
      member do 
        patch 'success'
        patch 'failed'
      end
    end
	end
  end

app/models/service_charge.rb
# == Schema Information
#
# Table name: service_charges
#
#  id         :bigint           not null, primary key
#  name       :string
#  price      :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ServiceCharge < ApplicationRecord
	has_many :orders
	validates :name, :presence => true,
    :on => [:update, :create]
    validates :price, :presence => true,
    :on => [:update, :create]
end

app/controllers/admins/service_charges_controller.rb
class Admins::ServiceChargesController < AdminsController
	before_action :set_posfee, only: [:show, :edit, :update, :destroy]

  # GET /posfees
  # GET /posfees.json
  def index
    @q = ServiceCharge.order(created_at: :desc).ransack(params[:q])
		@pagy, @service_charges = pagy(@q.result(distinct: true), items:20)
    
  end

  # GET /posfees/1
  # GET /posfees/1.json
  def show
  end

  # GET /posfees/new
  def new
    @service_charge = ServiceCharge.new
  end

  # GET /posfees/1/edit
  def edit
  end

  # POST /posfees
  # POST /posfees.json
  def create
    @service_charge = ServiceCharge.new(posfee_params)
      if @service_charge.save
      	redirect_to admins_pages_index_path, notice: 'Service Charge was successfully created.'
      else
        render 'new'
      end
  end

  # PATCH/PUT /posfees/1
  # PATCH/PUT /posfees/1.json
  def update
    respond_to do |format|
      if @service_charge.update(posfee_params)
        format.html { redirect_to admins_service_charges_path, notice: 'Service Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_charge }
      else
        format.html { render :edit }
        format.json { render json: @service_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posfees/1
  # DELETE /posfees/1.json
  def destroy
    @service_charge.destroy
    respond_to do |format|
      format.html { redirect_to admins_service_charges_path, notice: 'Service Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posfee
      @service_charge = ServiceCharge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def posfee_params
      params.require(:service_charge).permit(:name, :price)
    end
end

app/views/admins/service_charges/_form.html.erb
<div class="container">
  <h1><%=params[:action].capitalize%> Service Charge</h1>
  <div class="row">
    <div class="col-12">
      <%= simple_form_for [:admins, @service_charge] do |f| %>
        <div class="row">
          <div class="col-6">
            <%= f.input :name, disabled: true%>
          </div>
          <div class="col-6">
            <%= f.input :price %>
          </div>
          
        </div>
          <%= f.button :submit, class: "btn btn-info" %>

          <%= link_to "Cancel", admins_service_charges_path, class: "btn btn-danger" %>

      <% end %>
    </div>
  </div>
</div>

app/views/admins/service_charges/edit.html.erb
<%= render 'form'%>

app/views/admins/service_charges/index.html.erb
<div id="content-wrapper" class="d-flex flex-column">
  <!-- Main Content -->
  <div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h2 class="m-0 font-weight-bold">Service Charge Data</h2>
        </div>
          <div class="row">
            <div class="col-9">
              <%= search_form_for @q, url: admins_service_charges_path do |f| %>               
                <div class="row">
                  <div class="col-6">
                    <%= f.search_field :name_cont, placeholder: "Search by Service Charge Name", class: 'form-control admin-search' %>
                  </div>
                  <div class="col-3">
                    <%= f.button :Search, class: "btn btn-sm btn-success"%>     
                  </div>  
                </div>
              <%end%>
            </div>
          </div>
        </div>
          <div class="table-responsive">
          
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th class="th-sm"><%= sort_link(@q, :name) %></th>
                  <th class="th-sm"><%= sort_link(@q, :price) %></th>
                </tr>
              </thead>
              <tbody>
              <% @service_charges.each do |postal_fee| %>
                <tr>
                  <td><%= link_to postal_fee.name.titleize, edit_admins_service_charge_path(postal_fee)%></td>
                  <td><%= number_to_currency(postal_fee.price, :locale => :id) %></td>
                </tr>
              <% end %>
              </tbody>
              
            </table>
            <%== render partial: 'admins/shared/bootstrap_nav', locals: {pagy: @pagy} %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/service_charges/new.html.erb
<%= render 'form'%>