config/routes.rb
Rails.application.routes.draw do

  
#Customer
  root to: 'pages#index'
  get 'about', to: 'pages#about'
  get 'coupons/checking/:code', action: :checking, controller: 'coupons'
  post 'cekstatus', to: 'cart_products#check'

  resource :comments
  # resources :users, only: [:edit, :update]
  resources :users, only: :index do
    collection do
      get 'profile'
      put 'update'
    end
  end

  resources :wallet_statuses
  resources :carts do
    member do
      post 'create_transaction'
      post 'change_quantity'
    end
  end 
  
  resources :orders do
    member do
      patch 'cancel'
      patch "transition"
    end
  end

  resources :cart_products do
    member do
      post :change_quantity
    end
  end
  
  resources :notifications, only: [:index]

  devise_for :users
  resources :products do
    member do
        post 'add_cart_product'
        post 'create_comment'
      end
    end
  
  


	#ADMIN
	namespace :admins do
		get 'pages/index' => 'pages#index'
		resources :products do
      member do
        post "create_comment"
        patch 'set_active'
        patch 'set_deactive'
      end
    end

    resources :orders, except: [:new, :destroy] do
       member do
        get "input_receiver"
        get "input_receipt" 
        patch "transition"
      end
    end
    resources :notifications, only: [:index, :show]
    resources :extra_charges, only: [:edit, :update]

		resources :coupons
    resources :service_charges 
    resources :wallet_statuses, only: [:index, :edit, :update] do
      member do 
        patch 'success'
        patch 'failed'
      end
    end
	end
  end

app/views/shared/__header.html.erb
    <!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__cart">
            <% if user_signed_in? && current_user.customer? %>
              <ul>
                <li><a href="<%= orders_path%>"><i class="fas fa-receipt"></i></a></li>
                <li><a href="<%=cart_products_path%>"><i class="fa fa-shopping-bag"></i>
                    <span>
                      <%if current_user.carts.where(active:true).exists?%>
                        <%=current_user.carts.where(active:true).last.cart_products.count%>
                      <%else%>
                        0
                      <%end%>
                      0
                    </span></a></li>
              </ul>
            <%end%>
        </div>
        <div class="humberger__menu__widget">
            <div class="header__top__right__auth">
              <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt text-danger"></i> Logout
                <% end %>
              <% else %>
                <%= link_to new_user_session_path do %>
                  <i class="fa fa-user"></i> Login
                <% end %>
              <% end %>
            </div>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul class="nav">
              <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
              <li class="<%= 'active' if current_page?(cart_products_path) %>"><%= link_to "Shopping Cart", cart_products_path %></li>
              <li class="<%= 'active' if current_page?(orders_path) %>"><%= link_to "Order History", orders_path %></li>
          </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
          <a href="http://www.facebook.com" target="_blank"><i class="fab fa-facebook-f"></i></a>
          <a href="http://www.twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
          <a href="http://www.instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
        </div>
    </div>
    <!-- Humberger End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                  <div class="col-lg-6 col-md-6">
                    <div class="header__top__left">
                    </div>
                  </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                              <a href="http://www.facebook.com" target="_blank"><i class="fab fa-facebook-f"></i></a>
                              <a href="http://www.twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
                              <a href="http://www.instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
                            </div>
                           
                            <div class="header__top__right__auth">
                                <% if user_signed_in? %>
                              <%= link_to destroy_user_session_path, method: :delete do %>
                                <i class="fas fa-sign-out-alt text-danger"></i> Logout
                              <% end %>
                            <% else %>
                              <%= link_to new_user_session_path do %>
                                <i class="fa fa-user"></i> Login
                              <% end %>
                            <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <nav class="header__menu">
                        <ul class="nav">
                            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
                            <li class="<%= 'active' if current_page?(cart_products_path) %>"><%= link_to "Shopping Cart", cart_products_path %></li>
                            <li class="<%= 'active' if current_page?(orders_path) %>"><%= link_to "Order History", orders_path %></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-4">
                  <div class="header__cart">
                      <% if user_signed_in? && current_user.customer? %>
                        <ul>
                          <li><a href="<%=cart_products_path%>"><i class="fa fa-shopping-bag"></i>
                              <span>
                                <%if current_user.carts.where(active:true).exists?%>
                                  <%=current_user.carts.where(active:true).last.cart_products.count%>
                                <%else%>
                                  0
                                <%end%>
                                0
                              </span></a></li>
                          <li><a href="<%= wallet_statuses_path%>"><i class="fas fa-money-bill"></i></a></li>
                          <li><a href="<%= new_wallet_status_path%>"><%=number_to_currency(current_user.wallet.nominal, :locale => :id)%><i class="fas fa-plus"></i></a></li>
                        </ul>
                      <%end%>
                  </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>

app/views/shared/_footer.html.erb
<!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-6 col-sm-6">
                    <div class="footer__about">
                    <div class="footer__about__logo">
                            <a href="/"><img src=<%= asset_url('logo.png')%> alt=""></a>
                        </div>
                        <ul>
                            <li>Address: Jl. Rawa Belong, Jakarta</li>
                            <li>Phone: +6281912985860</li>
                            <li>Email: entice@gmail.com</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

app/views/shared/_header.html.erb
<!-- Humberger Begin -->
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
  <div class="humberger__menu__widget">
    <div>
      <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt text-danger"></i> Logout
          <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="fa fa-user"></i> Login
        <% end %>
        <br>
          <%=link_to new_user_registration_path do %>
            <i class="fa fa-user-plus"></i> Register
          <% end %>
      <% end %>
    </div>
  </div>
  <nav class="humberger__menu__nav mobile-menu">
    <ul class="nav">
      <li><%= link_to "Home", root_path %></li>
      <% if current_user.present? %>
        <li><%= link_to "Shopping Cart", cart_products_path %></li>
        <li><%= link_to "Order History", orders_path %></li>
      <% end %>
       <li><%= link_to "About", about_path %></li>
      <br>
      <br>
      <% if current_user.present? %>

      <li>
        <%= link_to notifications_path do %>
          <i class="fas fa-bell fa-fw"></i> Notification
          <!-- Counter - Alerts -->
          <span class="badge mobile badge-danger badge-counter"><%= current_user.notifications.where(read: false).count%></span>
        <% end %>
      </li>
      <li>
        <%= link_to new_wallet_status_path do %>
          <i class="fas fa-plus text-danger"></i> Top Up
        <% end %>
      </li>

      <li>
        <%= link_to wallet_statuses_path do %>
          <i class="fas fa-history text-danger"></i> Top Up History
        <% end %>
      </li>

      <li>
        <%= link_to profile_users_path do %>
          <i class="fas fa-user-edit text-danger"></i> Edit User
        <% end %>
      </li>
      <% end %>
    </ul>
  </nav>
  <div id="mobile-menu-wrap"></div>
</div>
<!-- Humberger End -->
<!-- Header Section Begin -->
<header class="header">
  <div class="header__top">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="header__top__left">
            <ul class="nav">
              <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
              <%if current_user.present?%>
                <li class="<%= 'active' if current_page?(cart_products_path) %>"><%= link_to "Shopping Cart", cart_products_path %></li>
                <li class="<%= 'active' if current_page?(orders_path) %>"><%= link_to "Order History", orders_path %></li>
              <%end%>
              <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <div class="header__top__right">
            <ul class="nav-bar">
              <%if current_user.present?%>
                <li class="nav-item dropdown no-arrow">
                  <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-bell fa-fw"></i>
                      <!-- Counter - Alerts -->
                      <span class="badge badge-danger badge-counter"><%= current_user.notifications.where(read: false).count%></span>
                  </a>
                  <!-- Dropdown - Alerts -->
                  <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                      aria-labelledby="alertsDropdown">
                      <h6 class="dropdown-header">
                          Notifications Center
                      </h6>
                      <% current_user.notifications.order(created_at: :desc).take(3).each do |notification| %>
                      <a class="dropdown-item d-flex align-items-center" href="<%=order_path(notification.order)%>">
                          <div class="notification-index">
                            <div class="mr-3">
                              <%if notification.read == false%>
                                <div class="icon-circle bg-primary"></div>
                              <%end%>
                            </div>
                            <div>
                                <div class="small text-gray-500"><%= notification.created_at.strftime("%b %d, %Y %H:%M")%></div>
                                <span><%= notification.message%></span>
                            </div>
                          </div>
                      </a>
                      <%end%>
                      </a>
                      <a class="dropdown-item text-center small text-gray-500" href="<%=notifications_path%>">Show All Notification</a>
                  </div>
              </li>
                <li><%=number_to_currency(current_user.wallet.nominal, :locale => :id)%></li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%=current_user.name.capitalize%>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="<%=new_wallet_status_path%>">
                      <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
                        Top Up
                    </a>
                    <a class="dropdown-item" href="<%=wallet_statuses_path%>">
                      <i class="fas fa-history fa-sm fa-fw mr-2 text-gray-400"></i>
                      Top Up History
                    </a>
                    <a class="dropdown-item" href="<%=profile_users_path%>">
                      <i class="fas fa-user-edit fa-sm fa-fw mr-2 text-gray-400"></i>
                      Edit Profile
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                  </div>
                </li>
              <%else%>
              <li>
                <%= link_to new_user_registration_path do %>
                  <i class="fa fa-user-plus"></i> Register
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                  <i class="fa fa-user"></i> Login
                <% end %>
              </li>
                 
              <%end%>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="humberger__open">
      <i class="fa fa-bars"></i>
    </div>
  </div>
</header>