config/routes.rb
Rails.application.routes.draw do

  
#Customer
  root to: 'pages#index'
  get 'about', to: 'pages#about'
  get 'coupons/checking/:code', action: :checking, controller: 'coupons'
  post 'cekstatus', to: 'cart_products#check'

  resource :comments
  # resources :users, only: [:edit, :update]
  resources :users, only: :index do
    collection do
      get 'profile'
      put 'update'
    end
  end

  resources :wallet_statuses
  resources :carts do
    member do
      post 'create_transaction'
      post 'change_quantity'
    end
  end 
  
  resources :orders do
    member do
      patch 'cancel'
      patch "transition"
    end
  end

  resources :cart_products do
    member do
      post :change_quantity
    end
  end
  
  resources :notifications, only: [:index]

  devise_for :users
  resources :products do
    member do
        post 'add_cart_product'
        post 'create_comment'
      end
    end
  
  


	#ADMIN
	namespace :admins do
		get 'pages/index' => 'pages#index'
		resources :products do
      member do
        post "create_comment"
        patch 'set_active'
        patch 'set_deactive'
      end
    end

    resources :orders, except: [:new, :destroy] do
       member do
        get "input_receiver"
        get "input_receipt" 
        patch "transition"
      end
    end
    resources :notifications, only: [:index, :show]
    resources :extra_charges, only: [:edit, :update]

		resources :coupons
    resources :service_charges 
    resources :wallet_statuses, only: [:index, :edit, :update] do
      member do 
        patch 'success'
        patch 'failed'
      end
    end
	end
  end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  description :text
#  image       :string
#  name        :string
#  price       :float
#  status      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  region_id   :bigint
#
# Indexes
#
#  index_products_on_region_id  (region_id)
#
class Product < ApplicationRecord
    belongs_to :region, dependent: :destroy

    has_many :cart_products, dependent: :nullify
    has_many :carts, :through => :cart_products

    has_many :comments
    mount_uploader :image, ImageUploader

    validates :name, :presence => true,
    :on => [:update, :create]
    validates :price, :presence => true,
    :on => [:update, :create]
    validates :status, :presence => true,
    :on => [:update, :create]
    validates :description, :presence => true,
    :on => [:update, :create]
    validates :region_id, :presence => true,
    :on => [:update, :create]

    enum status: {ready: 0, not_ready: 1}

    STATUS_OPTIONS=[
    	["Ready", 0],
    	["Not Ready", 1]
    ]
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < AdminsController

  before_action :set_product, only: [:show, :edit, :update, :destroy, :set_active, :set_deactive, :create_comment]

    def index
      @q = Product.order(status: :asc).ransack(params[:q])
		  @pagy, @products = pagy(@q.result(distinct: true), items:20)
    end

    def show
      @comments = Comment.where(product: @product).order(created_at: :desc)
    end

    
    def new
      @product = Product.new
    end

    
    def edit
    end

    
    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admins_products_path, notice: "Product #{@product.name} was successfully created."
      else
        render 'new'
      end
    end


    def update
      if @product.update(product_params)
        redirect_to admins_products_path, notice: "Product #{@product.name} was successfully updated."
      else
        render 'edit'
      end
    end


def destroy
  @product.destroy
  respond_to do |format|
    format.html { redirect_to admins_products_path, notice: "Product was successfully destroyed." }
    format.json { head :no_content }
  end
end

  def create_comment
    
    if params[:content][:message].present?
      Comment.create(content: params[:content][:message], user: current_user, product: @product)
      redirect_to admins_product_path(@product), notice: "Comment has been posted"
    else
      redirect_to admins_product_path(@product)
    end
  end

  def set_active
   @product.ready!
    redirect_to admins_products_path
  end

  def set_deactive
    @product.not_ready!
    redirect_to admins_products_path
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
        @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
        params.require(:product).permit(:name, :price, :image, :status, :region_id, :description)
    end

end

app/controllers/products_controller.rb
ActionView::Helpers::DateHelper

class ProductsController < ApplicationController
  before_action :set_product
  before_action :set_cart, only: [:add_cart_product]

  def show
    @comments = Comment.where(product: @product).order(created_at: :desc)
  end

  def add_cart_product
    if @cart.products.ids.include? params[:id].to_i
      if params[:product].present?
        @cart.cart_products.find_by(product_id: params[:id]).update(product:@product, quantity:params[:product][:qty])
      else
        @cart.cart_products.find_by(product_id: params[:id]).update(product:@product, quantity:1)
      end
    else
      if params[:product].present?
        @cart.cart_products.create(product:@product, quantity:params[:product][:qty])
      else
        @cart.cart_products.create(product:@product, quantity:1)
      end
    end
      flash[:notice] = 'Successfully put in to Cart'
      redirect_to cart_products_path
  end

  def create_comment
    
    if params[:content][:message].present?
      Comment.create(content: params[:content][:message], user: current_user, product: @product)
      redirect_to product_path(@product), notice: "Comment has been posted"
    else
      redirect_to product_path(@product)
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def set_cart
      if current_user.present?
        if current_user.carts.where(active:true).last.present?
          @cart = current_user.carts.where(active:true).last
        else
          @cart = current_user.carts.create(active:true, user:current_user)
        end
      else
        redirect_to  new_user_session_path 
      end
    end

    def product_params
      params.require(:product).permit(:price, :description, :name, :image, :status, :region_id)
    end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/__comment.html.erb
<div class="container mb-5 mt-5">
  <div class="card">
    <div class="row">
      <div class="col-md-12">
        <h3 class="text-center mb-5"> Nested comment section </h3>
        <div class="row">
          <div class="col-md-12">
            <div class="media"> 
              <div class="media-body">
                <div class="row">
                  <div class="col-8 d-flex">
                    <h5>Maria Smantha</h5>
                     <span>- 2 hours ago</span>
                  </div>
                  <div class="col-4">
                    <div class="pull-right reply"> <a href="#"><span><i class="fa fa-reply"></i> reply</span></a> </div>
                  </div>
                </div>
                 It is a long established fact that a reader will be distracted by the readable content of a page. 
                <div class="media mt-4"> <a class="pr-3" href="#"><img class="rounded-circle" alt="Bootstrap Media Another Preview" src="https://i.imgur.com/xELPaag.jpg" /></a>
                  <div class="media-body">
                    <div class="row">
                      <div class="col-12 d-flex">
                        <h5>Simona Disa</h5>
                         <span>- 3 hours ago</span>
                      </div>
                    </div>
                     letters, as opposed to using 'Content here, content here', making it look like readable English.
                  </div>
                </div>
                <div class="media mt-3"> <a class="pr-3" href="#"><img class="rounded-circle" alt="Bootstrap Media Another Preview" src="https://i.imgur.com/nAcoHRf.jpg" /></a>
                  <div class="media-body">
                    <div class="row">
                      <div class="col-12 d-flex">
                        <h5>John Smith</h5>
                         <span>- 4 hours ago</span>
                      </div>
                    </div>
                     the majority have suffered alteration in some form, by injected humour, or randomised words.
                  </div>
                </div>
              </div>
            </div>
            <div class="media mt-4"> <img class="mr-3 rounded-circle" alt="Bootstrap Media Preview" src="https://i.imgur.com/xELPaag.jpg" />
              <div class="media-body">
                <div class="row">
                  <div class="col-8 d-flex">
                    <h5>Shad f</h5>
                     <span>- 2 hours ago</span>
                  </div>
                  <div class="col-4">
                    <div class="pull-right reply"> <a href="#"><span><i class="fa fa-reply"></i> reply</span></a> </div>
                  </div>
                </div>
                 The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33. 
                <div class="media mt-4"> <a class="pr-3" href="#"><img class="rounded-circle" alt="Bootstrap Media Another Preview" src="https://i.imgur.com/nUNhspp.jpg" /></a>
                  <div class="media-body">
                    <div class="row">
                      <div class="col-12 d-flex">
                        <h5>Andy flowe</h5>
                         <span>- 5 hours ago</span>
                      </div>
                    </div>
                     Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
                  </div>
                </div>
                <div class="media mt-3"> <a class="pr-3" href="#"><img class="rounded-circle" alt="Bootstrap Media Another Preview" src="https://i.imgur.com/HjKTNkG.jpg" /></a>
                  <div class="media-body">
                    <div class="row">
                      <div class="col-12 d-flex">
                        <h5>Simp f</h5>
                         <span>- 5 hours ago</span>
                      </div>
                    </div>
                     a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur
                  </div>
                </div>
                <div class="media mt-3"> <a class="pr-3" href="#"><img class="rounded-circle" alt="Bootstrap Media Another Preview" src="https://i.imgur.com/nAcoHRf.jpg" /></a>
                  <div class="media-body">
                    <div class="row">
                      <div class="col-12 d-flex">
                        <h5>John Smith</h5>
                         <span>- 4 hours ago</span>
                      </div>
                    </div>
                     the majority have suffered alteration in some form, by injected humour, or randomised words.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/_comment.html.erb
<h6>Comments</h6>
<div class="container mb-5 mt-5">
  <div class="card">
    <div class="row">
      <div class="col-md-12">
        <h3 class="text-center mb-5"> Comment section </h3>
          <div class="row">
            <div class="col-md-12">
                <% @comments.each do |c|%>
                    <div class="media-body">
                        <div class="row">
                            <div class="col-8 d-flex">
                                <h5><%= c.user.name.titleize%></h5> <span>- <%= time_ago_in_words(c.created_at) + ' ago'%></span>
                            </div>
                        </div> 
                        <%= c.content %>
                    </div>
                <%end%>
            </div>
          </div>
          <div class="bg-light p-2">
            <%= form_tag create_comment_product_path, remote: true do %>
              <div class="content">
                <input type="text" class="form-control ml-1 shadow-none textarea" id="content_message" name="content[message]"></input>
              </div>                 
              <div class="mt-2 text-right">
                <button class="btn btn-primary btn-sm shadow-none">Post comment</button>
              </div>
            <%end%>
          </div>
          <!-- -->
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<!-- Product Details Section Begin -->
<section class="product-details spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6">
        <div class="product__details__pic">
          <div class="product__details__pic__item">
            <img class="product__details__pic__item--large"
                    src="<%=@product.image%>" alt="">
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="product__details__text">
          <h3><%=@product.name.capitalize%></h3>
          <div class="product__details__price"><%=number_to_currency(@product.price, :locale => :id)%></div>
          <h4><%=@product.region.name%></h4>
          
          <%= form_tag add_cart_product_product_path, remote: true do %>
            <div class="product__details__quantity">
              <div class="quantity">
                <div class="pro-qty">
                  <input type="text" value="1" id="product_qty" name="product[qty]">
                </div>
              </div>
            </div>
            <button class="primary-btn">ADD TO CART</button>
          <%end%>
          <ul>
            <li><b>Availability</b> <span><%= @product.status.titleize %></span></li>
            <li><b>Shipping</b> <span>1-2 Days of shipping</span></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="product__details__tab">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab"
                        aria-selected="true">Description</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab"
                        aria-selected="false">Comments</a>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active" id="tabs-1" role="tabpanel">
              <div class="product__details__tab__desc">
                <h6>Products Infomation</h6>
                <p><%= @product.description%></p>
              </div>
            </div>
            <div class="tab-pane" id="tabs-2" role="tabpanel">
              <div class="product__details__tab__desc">
                <%=render 'comment'%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Product Details Section End -->